server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hkpark130/spring_cloud.git
#          uri: file:///C:\Users\DIR-N-106\vagrant\spring\msa_shop